# Generated by Django 4.1.7 on 2023-03-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('add', models.TimeField(max_length=150)),
                ('ph', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
