# Generated by Django 4.1.7 on 2023-03-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_contact_add_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ph',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
